<a href="https://colab.research.google.com/github/srushtibhavsar/Gambling/blob/main/Hiwitask2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForCausalLM

In [2]:
! pip install accelerate

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.9/270.9 kB 5.9 MB/s eta 0:00:00


In [3]:
! huggingface-cli login
# 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


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Token: 
Add token as git credential? (Y/n) 
Token is valid (permission: write).
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credent

In [4]:
# Initialize the pipeline with LLaMA2 model

model_name = "meta-llama/Llama-2-7b-chat-hf"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

In [7]:
model = AutoModelForCausalLM.from_pretrained(model_name)

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

In [8]:
prompt = "write python basic code"

In [9]:
inputs = tokenizer(prompt, return_tensors="pt")

In [10]:
inputs

{'input_ids': tensor([[   1, 2436, 3017, 6996,  775]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [11]:
inputs = tokenizer.encode(prompt, return_tensors="pt")

In [12]:
inputs

tensor([[   1, 2436, 3017, 6996,  775]])

In [15]:
prompt = "write python basic code"
inputs = tokenizer.encode(prompt, return_tensors="pt")
outputs = model.generate(inputs, max_length=50,temperature = 0.0001)

completion = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(completion)

write python basic code for a simple web scraper

I am trying to write a simple web scraper in Python to extract some data from a website. Here is the code I have so far:
```
import requests
from bs


In [16]:
outputs[0]

tensor([    1,  2436,  3017,  6996,   775,   363,   263,  2560,  1856, 24559,
          546,    13,    13, 29902,   626,  1811,   304,  2436,   263,  2560,
         1856, 24559,   546,   297,  5132,   304,  6597,   777,   848,   515,
          263,  4700, 29889,  2266,   338,   278,   775,   306,   505,   577,
         2215, 29901,    13, 28956,    13,  5215,  7274,    13,  3166, 24512])

In [17]:
inputs

tensor([[   1, 2436, 3017, 6996,  775]])

In [18]:
tokens = tokenizer.tokenize(prompt)

In [19]:
tokens

['▁write', '▁python', '▁basic', '▁code']

In [20]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [21]:
ids

[2436, 3017, 6996, 775]

In [22]:
tokenizer.decode(ids)

'write python basic code'

In [23]:
completion

'write python basic code for a simple web scraper\n\nI am trying to write a simple web scraper in Python to extract some data from a website. Here is the code I have so far:\n```\nimport requests\nfrom bs'

In [24]:
def compute_number_tokens(string: str)-> int:
        inputs = tokenizer(string)
        #print(len(inputs["input_ids"]))
        return inputs

def _num_tokens_from_string(string: str) -> int:
        # Implement the method to compute the number of tokens for a string
        return len(compute_number_tokens(string)["input_ids"]) # Placeholder, replace with the actual token counting method

def _token_counter(result: str):
        # Extract total and completion tokens from Llama2's result
    total_tokens = len(result[0])   # tokens from both the prompt and the generated text
    #print(total_tokens)
    completion_tokens = total_tokens - _num_tokens_from_string(prompt) # Placeholder #  tokens that were specifically generated as part of the completion.
    return total_tokens, completion_tokens

def _completion(result: str):
    completion = tokenizer.decode(result[0], skip_special_tokens=True)
       #This method concatenates and returns the individual tokens from the first choice in the completion response. The tokens are extracted from the logprobs field, which suggests that it includes the tokens along with their log probabilities.
    return completion  # Placeholder, modify based on actual response format

In [25]:
prompt

'write python basic code'

In [26]:
_num_tokens_from_string(prompt)

5

In [27]:
tokenizer(completion)["input_ids"]

[1,
 2436,
 3017,
 6996,
 775,
 363,
 263,
 2560,
 1856,
 24559,
 546,
 13,
 13,
 29902,
 626,
 1811,
 304,
 2436,
 263,
 2560,
 1856,
 24559,
 546,
 297,
 5132,
 304,
 6597,
 777,
 848,
 515,
 263,
 4700,
 29889,
 2266,
 338,
 278,
 775,
 306,
 505,
 577,
 2215,
 29901,
 13,
 28956,
 13,
 5215,
 7274,
 13,
 3166,
 24512]

In [28]:
_token_counter(outputs)

(50, 45)

In [29]:
outputs

tensor([[    1,  2436,  3017,  6996,   775,   363,   263,  2560,  1856, 24559,
           546,    13,    13, 29902,   626,  1811,   304,  2436,   263,  2560,
          1856, 24559,   546,   297,  5132,   304,  6597,   777,   848,   515,
           263,  4700, 29889,  2266,   338,   278,   775,   306,   505,   577,
          2215, 29901,    13, 28956,    13,  5215,  7274,    13,  3166, 24512]])

In [31]:
logits = outputs.logits

AttributeError: 'Tensor' object has no attribute 'logits'

In [ ]:
logits

In [ ]:
probs = torch.softmax(logits, dim=-1)
# Take the log of probabilities to get log probabilities
log_probs = torch.log(probs)

In [ ]:
log_probs

NameError: name '_completion' is not defined

In [ ]:
generate_tex_pipeline = pipeline(
    model = model,
    tokenizer = tokenizer,
    return_full_text = True,
    task='text-generation',
    temperature =0,
    max_new_tokens = 512,

)

In [1]:
input_text = """
write a poem on tree:
Poem:
"""

SyntaxError: incomplete input (<ipython-input-1-cc3ec6cb3171>, line 1)

In [ ]:
res = generate_tex_pipeline(input_text)

In [ ]:
print(res[0]["generated_text"])