<a href="https://colab.research.google.com/github/srushtibhavsar/Gambling/blob/main/HuggingFace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The Pipeline Function

In [11]:
! pip install transformers

In [12]:
from transformers import pipeline

In [13]:
classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


In [14]:
classifier("I've been waiting for it for a long time")

[{'label': 'NEGATIVE', 'score': 0.9806705713272095}]

For more than one inputs

In [15]:
classifier(["I've been waiting for it for a long time","I love this"])

[{'label': 'NEGATIVE', 'score': 0.9806705713272095},
 {'label': 'POSITIVE', 'score': 0.9998819828033447}]

Zero-shot-classification

In [16]:
classifier = pipeline("zero-shot-classification")
classifier(
    "this course is about libraries",
    candidate_labels = ["education","politics","business"],
)

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'sequence': 'this course is about libraries',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.47363635897636414, 0.3429528474807739, 0.18341083824634552]}

Text Generation

In [17]:
generator = pipeline("text-generation")
generator("In this course we will teach you how to")

No model was supplied, defaulted to gpt2 and revision 6c0e608 (https://huggingface.co/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course we will teach you how to create anCertainValue() from a specific value. When you are creating anAnyKey() you know which keys will be assigned to each key as expected, a key is expected to be assigned to a specific'}]

Using different model

In [18]:
gen = pipeline("text-generation", model ="distilgpt2")

In [19]:
gen(
    "In this course, we will teach you how to",
    max_length = 30,
    num_return_sequences = 3,
)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course, we will teach you how to make your own coffee using different techniques.\n\n\n\nTo start with, I created an interesting'},
 {'generated_text': 'In this course, we will teach you how to build a simple game with a very simple design style in mind.\n\n\n\nI would like'},
 {'generated_text': 'In this course, we will teach you how to run an application against the Python and Django application, we will start with you to learn how to be'}]

Inside the Pipeline using pytorch

AutoTokenizer

In [20]:
from transformers import AutoTokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
raw_inputs = [
    "I've been waiting for the hugging face course my whole life",
    "I hate this so much",
 ]
inputs = tokenizer(raw_inputs, padding = True, truncation = True, return_tensors = "pt")

In [21]:
tokens = tokenizer.tokenize("let us try to tokenize")
print(tokens)

['let', 'us', 'try', 'to', 'token', '##ize']


In [22]:
inputs

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1996, 17662,  2227,
          2607,  2026,  2878,  2166,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   102,     0,     0,     0,
             0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}

Model (Download and cash the configuration of the model as well as pre-trained weights)

In [23]:
from transformers import AutoModel
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)
outputs = model(**inputs)

In [24]:
outputs

BaseModelOutput(last_hidden_state=tensor([[[-0.0173,  0.1092,  0.5693,  ...,  0.0518,  0.4603, -0.0276],
         [ 0.4720,  0.4316,  0.2974,  ...,  0.2525,  0.6922, -0.0837],
         [ 0.7922,  0.1065,  0.3860,  ...,  0.3879,  0.0451, -0.7868],
         ...,
         [ 0.4657,  0.2414,  0.4206,  ..., -0.2128,  0.6850, -0.2690],
         [ 0.4030,  0.4411,  0.3529,  ..., -0.0306,  0.5088, -0.1170],
         [ 0.2640,  0.2065,  0.3718,  ...,  0.4562,  0.4674, -0.6259]],

        [[-0.3088,  0.7332, -0.1861,  ..., -0.1305, -0.9360, -0.0433],
         [-0.3340,  0.9830, -0.0946,  ..., -0.3825, -0.6176,  0.2008],
         [-0.1687,  0.8781, -0.1117,  ..., -0.2380, -0.7790,  0.0935],
         ...,
         [-0.3022,  0.8105, -0.1694,  ..., -0.1124, -0.7401, -0.0543],
         [-0.3047,  0.7850, -0.2043,  ..., -0.1101, -0.7665, -0.0563],
         [-0.4014,  0.8999, -0.2245,  ..., -0.1877, -0.6910,  0.0329]]],
       grad_fn=<NativeLayerNormBackward0>), hidden_states=None, attentions=None)

In [25]:
print(outputs.last_hidden_state.shape)

torch.Size([2, 15, 768])


In [26]:
import torch

In [28]:
#predictions = torch.nn.functional.softmax(outputs.logits, dim = -1)
#print(predictions)

In [29]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

Inside the pipeline using tensorflow

In [30]:
from transformers import AutoTokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
raw_inputs = [
    "I've been waiting for the hugging face course my whole life",
    "I hate this so much",
 ]
inputs_tf = tokenizer(raw_inputs, padding = True, truncation = True, return_tensors = "tf")

In [31]:
inputs_tf

{'input_ids': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1996, 17662,
         2227,  2607,  2026,  2878,  2166,   102],
       [  101,  1045,  5223,  2023,  2061,  2172,   102,     0,     0,
            0,     0,     0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 15), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>}

In [32]:
from transformers import TFAutoModel #The TFAutoModel class loads a model without its pretraining head
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

In [33]:
model_tf = TFAutoModel.from_pretrained(checkpoint)
outputs_tf = model_tf(inputs_tf)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.weight', 'pre_classifier.bias', 'classifier.bias', 'pre_classifier.weight']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [34]:
outputs_tf.last_hidden_state.shape # returns ([batch size, sequence length, hidden size])

TensorShape([2, 15, 768])

In [35]:
print(outputs_tf)

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(2, 15, 768), dtype=float32, numpy=
array([[[-0.01730363,  0.10918023,  0.569317  , ...,  0.05181949,
          0.4603392 , -0.0276403 ],
        [ 0.4720258 ,  0.43155402,  0.2973982 , ...,  0.25252932,
          0.69224423, -0.08368975],
        [ 0.7922484 ,  0.10651433,  0.38599306, ...,  0.3879175 ,
          0.0451422 , -0.7868465 ],
        ...,
        [ 0.4657158 ,  0.24137631,  0.4206194 , ..., -0.2128381 ,
          0.6850013 , -0.26902765],
        [ 0.40298566,  0.4410672 ,  0.3529355 , ..., -0.03061504,
          0.5087621 , -0.11703645],
        [ 0.26395872,  0.20651174,  0.37177646, ...,  0.45622972,
          0.46738058, -0.6258714 ]],

       [[-0.30882266,  0.73317593, -0.18605003, ..., -0.1305379 ,
         -0.936004  , -0.04329737],
        [-0.3339702 ,  0.98304313, -0.09462029, ..., -0.38247427,
         -0.6175631 ,  0.20076793],
        [-0.16871406,  0.87811613, -0.1116586 , ..., -0.23800442,
         -0.7

In [36]:
print(dir(outputs_tf))

['__annotations__', '__class__', '__class_getitem__', '__contains__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__or__', '__post_init__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'attentions', 'clear', 'copy', 'fromkeys', 'get', 'hidden_states', 'items', 'keys', 'last_hidden_state', 'move_to_end', 'pop', 'popitem', 'setdefault', 'to_tuple', 'update', 'values']


In [37]:
#outputs_tf.logits
#import tensorflow as tf
#predict = tf.math.softmax(outputs_tf.logits,axis=1)
#print(predict)

AutoModel class allows you to instantiate a pretrained model from any checkpoint on hugging face hub. It will pich the right model class from the library to instantiate the proper architecture and load the weights of the pretrained model inside it

The AutoConfig API allows you to instantiate the configuration of a pretrained model from any checkpoint

Configuration of the model is the blueprint that contains all the information necessary to create  the model architecture

In [38]:
from transformers import BertConfig
bert_config = BertConfig.from_pretrained("bert-base-cased")
print(bert_config)

BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.33.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}



Same architecture as bert-base-cased

In [39]:
from transformers import BertConfig, BertModel
bert_config = BertConfig.from_pretrained("bert-base-cased")
bert_model = BertModel(bert_config)

Using only 10 layers instead of 12

In [40]:
from transformers import BertConfig, BertModel
bert_config = BertConfig.from_pretrained("bert-base-cased", num_hidden_layers = 10)
bert_model = BertModel(bert_config)

Saving a model

In [41]:
bert_model.save_pretrained("my-bert-model")

Reloading a saved model

In [42]:
from transformers import BertModel
bert_model = BertModel.from_pretrained("my-bert-model")

With tensorflow

In [43]:
from transformers import BertConfig, TFBertModel
bert_config = BertConfig.from_pretrained("bert-base-cased")
bert_model_tf = TFBertModel(bert_config)
bert_model_tf.save_pretrained("my-tf-bert-model")

In [44]:
from transformers import TFBertModel
bert_model_tf_loaded = TFBertModel.from_pretrained("my-tf-bert-model")

All model checkpoint layers were used when initializing TFBertModel.

Some layers of TFBertModel were not initialized from the model checkpoint at my-tf-bert-model and are newly initialized: ['bert/encoder/layer_._5/attention/self/query/kernel:0', 'bert/encoder/layer_._0/attention/output/dense/bias:0', 'bert/encoder/layer_._9/output/LayerNorm/gamma:0', 'bert/encoder/layer_._4/attention/self/query/bias:0', 'bert/encoder/layer_._0/attention/self/query/kernel:0', 'bert/encoder/layer_._8/attention/output/LayerNorm/beta:0', 'bert/encoder/layer_._1/attention/self/key/kernel:0', 'bert/encoder/layer_._6/output/LayerNorm/gamma:0', 'bert/encoder/layer_._9/intermediate/dense/bias:0', 'bert/encoder/layer_._10/attention/self/key/bias:0', 'bert/encoder/layer_._4/output/LayerNorm/beta:0', 'bert/encoder/layer_._0/attention/output/LayerNorm/beta:0', 'bert/encoder/layer_._5/attention/self/query/bias:0', 'bert/encoder/layer_._1/attention/self/key/bias:0', 'bert/encoder/layer_._0/attention/self/value/kern

Batching inputs together

In [45]:
from transformers import AutoTokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
sentences = [
    "I've been waiting for the hugging face course my whole life",
    "I hate this so much",
 ]
tokens = [tokenizer.tokenize(sentence) for sentence in sentences]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokens]
print(ids[0])
print(ids[1])

[1045, 1005, 2310, 2042, 3403, 2005, 1996, 17662, 2227, 2607, 2026, 2878, 2166]
[1045, 5223, 2023, 2061, 2172]


In [46]:
print(tokenizer(sentences, padding=True))

{'input_ids': [[101, 1045, 1005, 2310, 2042, 3403, 2005, 1996, 17662, 2227, 2607, 2026, 2878, 2166, 102], [101, 1045, 5223, 2023, 2061, 2172, 102, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}


Dataset Overview

In [47]:
! pip install datasets

In [48]:
from datasets import load_dataset

In [49]:
raw_datasets = load_dataset("glue","mrpc")
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 408
    })
    test: Dataset({
        features: ['sentence1', 'sentence2', 'label', 'idx'],
        num_rows: 1725
    })
})

In [50]:
raw_datasets["train"]

Dataset({
    features: ['sentence1', 'sentence2', 'label', 'idx'],
    num_rows: 3668
})

In [51]:
raw_datasets["train"].features

{'sentence1': Value(dtype='string', id=None),
 'sentence2': Value(dtype='string', id=None),
 'label': ClassLabel(names=['not_equivalent', 'equivalent'], id=None),
 'idx': Value(dtype='int32', id=None)}

In [52]:
raw_datasets["train"][:5]

{'sentence1': ['Amrozi accused his brother , whom he called " the witness " , of deliberately distorting his evidence .',
  "Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .",
  'They had published an advertisement on the Internet on June 10 , offering the cargo for sale , he added .',
  'Around 0335 GMT , Tab shares were up 19 cents , or 4.4 % , at A $ 4.56 , having earlier set a record high of A $ 4.57 .',
  'The stock rose $ 2.11 , or about 11 percent , to close Friday at $ 21.51 on the New York Stock Exchange .'],
 'sentence2': ['Referring to him as only " the witness " , Amrozi accused his brother of deliberately distorting his evidence .',
  "Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .",
  "On June 10 , the ship 's owners had published an advertisement on the Internet , offering the explosives for sale .",
  'Tab shares jumped 20 cents , or 4.6 % , to set a record closing high at 

In [53]:
from transformers import AutoTokenizer
checkpoint ="bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
  return tokenizer(
      example["sentence1"], example["sentence2"], padding = "max_length", truncation = True, max_length = 128
  )

tokenized_dataset = raw_datasets.map(tokenize_function,batched = True)

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

In [54]:
tokenized_dataset = tokenized_dataset.remove_columns(["idx","sentence1","sentence2"])
tokenized_dataset = tokenized_dataset.rename_column("label","labels")
tokenized_dataset = tokenized_dataset.with_format("torch")

In [55]:
tokenized_dataset["train"]

Dataset({
    features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 3668
})

Preprocessing sentence pairs

In [56]:
from transformers import AutoTokenizer

In [57]:
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
tokenizer("My name is Srushti","I work at SE chair")

{'input_ids': [101, 2026, 2171, 2003, 5034, 20668, 3775, 102, 1045, 2147, 2012, 7367, 3242, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

Token_type_ids tells which token belongs to the first sentence and which belongs to the second sentence

In [58]:
tokenizer(
          ["My name is Srushti","going to cinema"],
          ["I work at SE chair", "This movie is great"],
          padding = True
          )

{'input_ids': [[101, 2026, 2171, 2003, 5034, 20668, 3775, 102, 1045, 2147, 2012, 7367, 3242, 102], [101, 2183, 2000, 5988, 102, 2023, 3185, 2003, 2307, 102, 0, 0, 0, 0]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]}

using Pytorch

In [59]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
checkpoint = "bert-base-uncased"
model = AutoModel.from_pretrained(checkpoint)
batch = tokenizer(
    ["My name is Srushti","going to cinema"],
    ["I work at SE chair", "This movie is great"],
    padding = True,
    return_tensors = "pt",
)

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**batch)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Using Tensorflow

In [60]:
from transformers import TFAutoModelForSequenceClassification, AutoTokenizer
checkpoint = "bert-base-uncased"
model = AutoModel.from_pretrained(checkpoint)
batch = tokenizer(
    ["My name is Srushti","going to cinema"],
    ["I work at SE chair", "This movie is great"],
    padding = True,
    return_tensors = "tf",
)

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**batch)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Dynamic padding

In [61]:
import torch.utils

In [62]:
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer)
train_dataloader = DataLoader(
    tokenized_dataset["train"], batch_size= 16,shuffle= True, collate_fn = data_collator
    )
for step, batch in enumerate(train_dataloader):
  print(batch["input_ids"].shape)
  if step>5:
    break

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])
torch.Size([16, 128])


In [63]:
from transformers import AutoTokenizer
from datasets import load_dataset

raw_datasets = load_dataset("glue","mrpc")
checkpoint ="bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
  return tokenizer(
      example["sentence1"], example["sentence2"], truncation = True
  )

tokenized_dataset = raw_datasets.map(tokenize_function,batched = True)
tokenized_dataset = tokenized_dataset.remove_columns(["idx","sentence1","sentence2"])
tokenized_dataset = tokenized_dataset.rename_column("label","labels")
tokenized_dataset = tokenized_dataset.with_format("torch")

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

In [64]:
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer)
train_dataloader = DataLoader(
    tokenized_dataset["train"], batch_size= 16,shuffle= True, collate_fn = data_collator
    )
for step, batch in enumerate(train_dataloader):
  print(batch["input_ids"].shape)
  if step>5:
    break

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


torch.Size([16, 69])
torch.Size([16, 73])
torch.Size([16, 77])
torch.Size([16, 81])
torch.Size([16, 77])
torch.Size([16, 75])
torch.Size([16, 78])


The Trainer API

In [65]:
from transformers import AutoTokenizer, DataCollatorWithPadding
from datasets import load_dataset

raw_datasets = load_dataset("glue","mrpc")
checkpoint ="bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
  return tokenizer(
      example["sentence1"], example["sentence2"], truncation = True
  )

tokenized_dataset = raw_datasets.map(tokenize_function,batched = True)
data_collator = DataCollatorWithPadding(tokenizer)

In [66]:
! pip install transformers[torch]

create trainer

In [67]:
! pip install accelerate -U

In [68]:
from transformers import AutoModelForSequenceClassification
from transformers import AutoTokenizer
from datasets import load_dataset

raw_datasets = load_dataset("glue","mrpc")
checkpoint ="bert-base-cased"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=2)

from transformers import TrainingArguments
training_args = TrainingArguments("test-trainer")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Cutomized All parameters

In [69]:
training_args = TrainingArguments(
    "test-trainer",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    learning_rate=2e-5,
    weight_decay=0.01,
)

In [70]:
from transformers import AutoTokenizer
checkpoint ="bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_function(example):
  return tokenizer(
      example["sentence1"], example["sentence2"], padding = "max_length", truncation = True, max_length = 128
  )

tokenized_dataset = raw_datasets.map(tokenize_function,batched = True)

In [71]:
from transformers import Trainer

trainer = Trainer(
    model,
    training_args,
    train_dataset = tokenized_dataset["train"],
    eval_dataset = tokenized_dataset["validation"],
    data_collator = data_collator,
    tokenizer = tokenizer,
)
trainer.train()

You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


TrainOutput(global_step=1150, training_loss=0.21669500350952148, metrics={'train_runtime': 434.5135, 'train_samples_per_second': 42.208, 'train_steps_per_second': 2.647, 'total_flos': 1206364188825600.0, 'train_loss': 0.21669500350952148, 'epoch': 5.0})

In [72]:
predictions = trainer.predict(tokenized_dataset["validation"])
print(predictions.predictions.shape, predictions.label_ids.shape)

(408, 2) (408,)


In [80]:
import numpy as np
from datasets import load_metric

metric = load_metric("glue","mrpc")
preds = np.argmax(predictions.predictions,axis =-1)
metric.compute(predictions= preds, references= predictions.label_ids)

{'accuracy': 0.8504901960784313, 'f1': 0.8950086058519794}

In [81]:
def compute_metrics(eval_preds):
  logits,labels = eval_preds
  predictions = np.argmax(logits,axis =-1)
  return metric.compute(predictions = predictions, reference = labels)

In [82]:
training_args = TrainingArguments("test-trainer", evaluation_strategy = "epoch")
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels = 2)
trainer = Trainer(
    model,
    training_args,
    train_dataset = tokenized_dataset["train"],
    eval_dataset = tokenized_dataset["validation"],
    data_collator = data_collator,
    tokenizer = tokenizer,
    compute_metrics = compute_metrics
)


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
